-- ============================================================
-- SCRIPT DE CREACIÓN DE BASE DE DATOS Y TABLAS (C# / .NET)
-- ============================================================

-- NOTA: Ejecutar este bloque inicial conectado al servidor PostgreSQL (base 'postgres')
-- CREATE DATABASE "ISW-312-PROJ1";

-- Conéctate a la base de datos "ISW-312-PROJ1" antes de ejecutar lo siguiente:

-- 1. Crear Esquemas
CREATE SCHEMA IF NOT EXISTS inventory;
CREATE SCHEMA IF NOT EXISTS sales;
CREATE SCHEMA IF NOT EXISTS purchases;

-- 2. Habilitar Extensión de Criptografía
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- 3. Crear Historiales de Migraciones de EF Core
CREATE TABLE IF NOT EXISTS inventory."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

CREATE TABLE IF NOT EXISTS sales."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

CREATE TABLE IF NOT EXISTS purchases."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

-- ============================================================
-- TABLAS DEL ESQUEMA: inventory
-- ============================================================

CREATE TABLE IF NOT EXISTS inventory.companies (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    cen uuid NOT NULL DEFAULT gen_random_uuid(),
    name text NOT NULL,
    nit text,
    phone text,
    email text,
    address text,
    city text,
    country text,
    active boolean NOT NULL DEFAULT true,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "PK_companies" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS inventory.categories (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    cen uuid NOT NULL DEFAULT gen_random_uuid(),
    company_id integer NOT NULL,
    company_cen uuid NOT NULL,
    code text NOT NULL,
    name text NOT NULL,
    description text,
    active boolean NOT NULL DEFAULT true,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "PK_categories" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS inventory.units_measure (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    cen uuid NOT NULL DEFAULT gen_random_uuid(),
    code text NOT NULL,
    name text NOT NULL,
    abbreviation text,
    active boolean NOT NULL DEFAULT true,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "PK_units_measure" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS inventory.products (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    cen uuid NOT NULL DEFAULT gen_random_uuid(),
    company_id integer NOT NULL,
    company_cen uuid NOT NULL,
    code text NOT NULL,
    sku text NOT NULL,
    name text NOT NULL,
    description text,
    category_id integer,
    category_cen uuid,
    unit_measure_id integer,
    unit_measure_cen uuid,
    price numeric(12,2) NOT NULL,
    cost numeric(12,2) NOT NULL,
    track_stock boolean NOT NULL DEFAULT false,
    is_out_of_stock boolean NOT NULL DEFAULT false,
    active boolean NOT NULL DEFAULT true,
    station_code text DEFAULT 'COCINA',
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "PK_products" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS inventory.locations (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    cen uuid NOT NULL DEFAULT gen_random_uuid(),
    company_id integer NOT NULL,
    company_cen uuid NOT NULL,
    code text NOT NULL,
    name text NOT NULL,
    address text,
    phone text,
    active boolean NOT NULL DEFAULT true,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "PK_locations" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS inventory.warehouses (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    cen uuid NOT NULL DEFAULT gen_random_uuid(),
    company_id integer NOT NULL,
    company_cen uuid NOT NULL,
    location_id integer NOT NULL,
    location_cen uuid NOT NULL,
    code text NOT NULL,
    name text NOT NULL,
    description text,
    active boolean NOT NULL DEFAULT true,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "PK_warehouses" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS inventory.stock (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    cen uuid NOT NULL DEFAULT gen_random_uuid(),
    company_id integer NOT NULL,
    company_cen uuid NOT NULL,
    location_id integer NOT NULL,
    location_cen uuid NOT NULL,
    warehouse_id integer NOT NULL,
    warehouse_cen uuid NOT NULL,
    product_id integer NOT NULL,
    product_cen uuid NOT NULL,
    quantity numeric(12,2) NOT NULL DEFAULT 0,
    min_quantity numeric(12,2) NOT NULL DEFAULT 0,
    max_quantity numeric(12,2),
    last_counted_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "PK_stock" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS inventory.movement_types (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    cen uuid NOT NULL DEFAULT gen_random_uuid(),
    code text NOT NULL,
    name text NOT NULL,
    "Description" text,
    movement_direction text NOT NULL,
    active boolean NOT NULL DEFAULT true,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "PK_movement_types" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS inventory.movements (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    cen uuid NOT NULL DEFAULT gen_random_uuid(),
    company_id integer NOT NULL,
    company_cen uuid NOT NULL,
    location_id integer NOT NULL,
    location_cen uuid NOT NULL,
    warehouse_id integer NOT NULL,
    warehouse_cen uuid NOT NULL,
    product_id integer NOT NULL,
    product_cen uuid NOT NULL,
    movement_type_id integer NOT NULL,
    movement_type_cen uuid NOT NULL,
    quantity numeric(12,2) NOT NULL,
    balance_before numeric(12,2) NOT NULL,
    balance_after numeric(12,2) NOT NULL,
    reference text,
    notes text,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "PK_movements" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS inventory.operation_documents (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    cen uuid NOT NULL DEFAULT gen_random_uuid(),
    company_id integer NOT NULL,
    company_cen uuid NOT NULL,
    location_id integer NOT NULL,
    location_cen uuid NOT NULL,
    warehouse_id integer NOT NULL,
    warehouse_cen uuid NOT NULL,
    document_number text NOT NULL,
    operation_type text NOT NULL,
    status text NOT NULL,
    reference text,
    notes text,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    confirmed_at timestamp with time zone,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "PK_operation_documents" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS inventory.operation_document_items (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    cen uuid NOT NULL DEFAULT gen_random_uuid(),
    document_id integer NOT NULL,
    document_cen uuid NOT NULL,
    product_id integer NOT NULL,
    product_cen uuid NOT NULL,
    quantity numeric(12,2) NOT NULL,
    notes text,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "PK_operation_document_items" PRIMARY KEY (id),
    CONSTRAINT "FK_operation_document_items_operation_documents_document_id" FOREIGN KEY (document_id) REFERENCES inventory.operation_documents (id) ON DELETE CASCADE
);

-- ============================================================
-- TABLAS DEL ESQUEMA: sales
-- ============================================================

CREATE TABLE IF NOT EXISTS sales."Company" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Cen" uuid NOT NULL DEFAULT gen_random_uuid(),
    "Name" text NOT NULL,
    CONSTRAINT "PK_Company" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS sales."Location" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Cen" uuid NOT NULL DEFAULT gen_random_uuid(),
    "CompanyId" integer NOT NULL,
    "CompanyCen" uuid NOT NULL,
    "Name" text NOT NULL,
    CONSTRAINT "PK_Location" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS sales."Vendor" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Cen" uuid NOT NULL DEFAULT gen_random_uuid(),
    "CompanyId" integer NOT NULL,
    "CompanyCen" uuid NOT NULL,
    "Name" text NOT NULL,
    "Email" text,
    "Phone" text,
    "IsWaiter" boolean NOT NULL DEFAULT false,
    "Active" boolean NOT NULL DEFAULT true,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "PK_Vendor" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS sales."Ticket" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Cen" uuid NOT NULL DEFAULT gen_random_uuid(),
    "CompanyId" integer NOT NULL,
    "CompanyCen" uuid NOT NULL,
    "LocationId" integer NOT NULL,
    "LocationCen" uuid NOT NULL,
    "TicketNumber" text NOT NULL,
    "VendorId" integer,
    "VendorCen" uuid,
    "TableCode" text,
    "Status" text NOT NULL,
    CONSTRAINT "PK_Ticket" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS sales."TicketItem" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Cen" uuid NOT NULL DEFAULT gen_random_uuid(),
    "TicketId" integer NOT NULL,
    "TicketCen" uuid NOT NULL,
    "ProductId" integer NOT NULL,
    "ProductCen" uuid NOT NULL,
    "Quantity" numeric(12,2) NOT NULL DEFAULT 1,
    "UnitPrice" numeric(12,2) NOT NULL DEFAULT 0,
    "Status" text NOT NULL,
    "Notes" text,
    CONSTRAINT "PK_TicketItem" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_TicketItem_Ticket_TicketId" FOREIGN KEY ("TicketId") REFERENCES sales."Ticket" ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS sales."Payment" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Cen" uuid NOT NULL DEFAULT gen_random_uuid(),
    "TicketId" integer NOT NULL,
    "TicketCen" uuid NOT NULL,
    "PaymentMethod" text NOT NULL,
    "Amount" numeric(12,2) NOT NULL,
    "Reference" text,
    "PaidBy" text,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "PK_Payment" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Payment_Ticket_TicketId" FOREIGN KEY ("TicketId") REFERENCES sales."Ticket" ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS sales.tax_configuration (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    cen uuid NOT NULL DEFAULT gen_random_uuid(),
    company_cen uuid NOT NULL,
    tax_rate numeric(5,2) NOT NULL DEFAULT 0.18,
    CONSTRAINT "PK_tax_configuration" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS sales.command_stations (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    cen uuid NOT NULL DEFAULT gen_random_uuid(),
    company_id integer NOT NULL,
    company_cen uuid NOT NULL,
    code text NOT NULL,
    name text NOT NULL,
    station_type text NOT NULL,
    description text,
    active boolean NOT NULL DEFAULT true,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "PK_command_stations" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS sales.commands (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    cen uuid NOT NULL DEFAULT gen_random_uuid(),
    company_id integer NOT NULL,
    company_cen uuid NOT NULL,
    location_id integer NOT NULL,
    location_cen uuid NOT NULL,
    ticket_id integer NOT NULL,
    ticket_cen uuid NOT NULL,
    station_id integer NOT NULL,
    station_cen uuid NOT NULL,
    command_number text NOT NULL,
    status text NOT NULL,
    is_reorder boolean NOT NULL DEFAULT false,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    sent_at timestamp with time zone,
    ready_at timestamp with time zone,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "PK_commands" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_commands_Ticket" FOREIGN KEY (ticket_id) REFERENCES sales."Ticket" ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS sales.command_items (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    cen uuid NOT NULL DEFAULT gen_random_uuid(),
    command_id integer NOT NULL,
    command_cen uuid NOT NULL,
    ticket_item_id integer NOT NULL,
    ticket_item_cen uuid NOT NULL,
    product_id integer NOT NULL,
    product_cen uuid NOT NULL,
    quantity numeric(12,2) NOT NULL,
    status text NOT NULL,
    notes text,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "PK_command_items" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_command_items_commands_command_id" FOREIGN KEY (command_id) REFERENCES sales.commands ("Id") ON DELETE CASCADE
);

-- ============================================================
-- TABLAS DEL ESQUEMA: purchases
-- ============================================================

CREATE TABLE IF NOT EXISTS purchases.orders (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    cen uuid NOT NULL DEFAULT gen_random_uuid(),
    company_id integer NOT NULL,
    company_cen uuid NOT NULL,
    supplier text NOT NULL,
    supplier_cen uuid,
    date timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    status text NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "PK_orders" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS purchases.order_items (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    cen uuid NOT NULL DEFAULT gen_random_uuid(),
    order_id integer NOT NULL,
    order_cen uuid NOT NULL,
    product_id integer NOT NULL,
    product_cen uuid NOT NULL,
    quantity numeric(12,2) NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "PK_order_items" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_order_items_orders_order_id" FOREIGN KEY (order_id) REFERENCES purchases.orders ("Id") ON DELETE CASCADE
);

-- TABLA DE PROVEEDORES
CREATE TABLE IF NOT EXISTS purchases.suppliers (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    company_id integer NOT NULL,
    code text NOT NULL,
    name text NOT NULL,
    active boolean NOT NULL DEFAULT true,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "PK_suppliers" PRIMARY KEY (id)
);

-- ============================================================
-- ÍNDICES Y CONSTRICCIONES
-- ============================================================

-- Índices: inventory
CREATE UNIQUE INDEX IF NOT EXISTS "IX_categories_cen" ON inventory.categories (cen);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_categories_company_cen_code" ON inventory.categories (company_cen, code);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_companies_cen" ON inventory.companies (cen);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_locations_cen" ON inventory.locations (cen);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_movement_types_cen" ON inventory.movement_types (cen);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_movements_cen" ON inventory.movements (cen);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_operation_document_items_cen" ON inventory.operation_document_items (cen);
CREATE INDEX IF NOT EXISTS "IX_operation_document_items_document_id" ON inventory.operation_document_items (document_id);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_operation_documents_cen" ON inventory.operation_documents (cen);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_products_cen" ON inventory.products (cen);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_products_company_cen_code" ON inventory.products (company_cen, code);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_stock_cen" ON inventory.stock (cen);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_units_measure_cen" ON inventory.units_measure (cen);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_warehouses_cen" ON inventory.warehouses (cen);

-- Índices: sales
CREATE UNIQUE INDEX IF NOT EXISTS "IX_command_items_cen" ON sales.command_items (cen);
CREATE INDEX IF NOT EXISTS "IX_command_items_command_id" ON sales.command_items (command_id);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_command_stations_cen" ON sales.command_stations (cen);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_commands_cen" ON sales.commands (cen);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_Company_Cen" ON sales."Company" ("Cen");
CREATE UNIQUE INDEX IF NOT EXISTS "IX_Location_Cen" ON sales."Location" ("Cen");
CREATE UNIQUE INDEX IF NOT EXISTS "IX_Payment_Cen" ON sales."Payment" ("Cen");
CREATE UNIQUE INDEX IF NOT EXISTS "IX_tax_configuration_company_cen" ON sales.tax_configuration (company_cen);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_Ticket_Cen" ON sales."Ticket" ("Cen");
CREATE UNIQUE INDEX IF NOT EXISTS "IX_TicketItem_Cen" ON sales."TicketItem" ("Cen");
CREATE INDEX IF NOT EXISTS "IX_TicketItem_TicketId" ON sales."TicketItem" ("TicketId");
CREATE UNIQUE INDEX IF NOT EXISTS "IX_Vendor_Cen" ON sales."Vendor" ("Cen");

-- Índices: purchases
CREATE UNIQUE INDEX IF NOT EXISTS "IX_order_items_cen" ON purchases.order_items (cen);
CREATE INDEX IF NOT EXISTS "IX_order_items_order_id" ON purchases.order_items (order_id);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_orders_cen" ON purchases.orders (cen);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_suppliers_company_id_code" ON purchases.suppliers (company_id, code);

-- ============================================================
-- REGISTRO DE HISTORIAL DE MIGRACIONES EN EF CORE
-- ============================================================
INSERT INTO inventory."__EFMigrationsHistory" ("MigrationId", "ProductVersion") VALUES ('20260518023624_InitialCreate', '9.0.4') ON CONFLICT DO NOTHING;
INSERT INTO sales."__EFMigrationsHistory" ("MigrationId", "ProductVersion") VALUES ('20260518023627_InitialCreate', '9.0.4') ON CONFLICT DO NOTHING;
INSERT INTO purchases."__EFMigrationsHistory" ("MigrationId", "ProductVersion") VALUES ('20260518023623_InitialCreate', '9.0.4') ON CONFLICT DO NOTHING;
INSERT INTO purchases."__EFMigrationsHistory" ("MigrationId", "ProductVersion") VALUES ('20260522233555_CreateSuppliersTable', '9.0.4') ON CONFLICT DO NOTHING;
