services:
  postgres-db:
    image: postgres:15-alpine
    container_name: fastinventory-db
    environment:
      POSTGRES_USER: ${DB_USER:-admin}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-secret_password}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d

  inventory-api:
    build: ./ISW-312-Inventory.Api
    container_name: inventory-api-srv
    ports:
      - "5143:8080"
    environment:
      - DB_CONNECTION_STRING=${DB_CONNECTION_STRING}
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
    depends_on:
      - postgres-db

  purchase-api:
    build: ./ISW-312-Purchases.Api
    container_name: purchase-api-srv
    ports:
      - "5085:8080"
    environment:
      - DB_CONNECTION_STRING=${DB_CONNECTION_STRING}
      - INVENTORY_API_URL=${INVENTORY_API_URL}
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
    depends_on:
      - postgres-db

  sale-api:
    build: ./ISW-312-Sales.Api
    container_name: sale-api-srv
    ports:
      - "5074:8080"
    environment:
      - DB_CONNECTION_STRING=${DB_CONNECTION_STRING}
      - INVENTORY_API_URL=${INVENTORY_API_URL}
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
    depends_on:
      - postgres-db

  web-app:
    build:
      context: ./ISW-312-frontend
      args:
        - VITE_INVENTORY_API_URL=${VITE_INVENTORY_API_URL}
        - VITE_PURCHASES_API_URL=${VITE_PURCHASES_API_URL}
        - VITE_SALES_API_URL=${VITE_SALES_API_URL}
    container_name: web-page-srv
    ports:
      - "3000:80"
    depends_on:
      - inventory-api
      - purchase-api
      - sale-api

volumes:
  pgdata:
