apiVersion: v1
kind: ConfigMap
metadata:
  name: purchases-api-config
  namespace: default
data:
  INVENTORY_API_URL: "http://inventory-api-srv:8080"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: purchases-api-deploy
  namespace: default
  labels:
    app: purchases-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: purchases-api
  template:
    metadata:
      labels:
        app: purchases-api
    spec:
      containers:
      - name: purchases-api
        image: mokachin123/pdv-purchases-api:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "256Mi"
        env:
        - name: INVENTORY_API_URL
          valueFrom:
            configMapKeyRef:
              name: purchases-api-config
              key: INVENTORY_API_URL
        - name: DB_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: purchases-api-secrets
              key: DB_CONNECTION_STRING
        livenessProbe:
          httpGet:
            path: /swagger/index.html
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /swagger/index.html
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: purchases-api-srv
  namespace: default
spec:
  selector:
    app: purchases-api
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30085
  type: NodePort
