DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'inventory') THEN
        CREATE SCHEMA inventory;
    END IF;
END $EF$;
CREATE TABLE IF NOT EXISTS inventory."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'inventory') THEN
        CREATE SCHEMA inventory;
    END IF;
END $EF$;

CREATE TABLE inventory.categories (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    cen uuid NOT NULL,
    company_id integer NOT NULL,
    company_cen uuid NOT NULL,
    code text NOT NULL,
    name text NOT NULL,
    description text,
    active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT "PK_categories" PRIMARY KEY (id)
);

CREATE TABLE inventory.companies (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    cen uuid NOT NULL,
    name text NOT NULL,
    nit text,
    phone text,
    email text,
    address text,
    city text,
    country text,
    active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT "PK_companies" PRIMARY KEY (id)
);

CREATE TABLE inventory.locations (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    cen uuid NOT NULL,
    company_id integer NOT NULL,
    company_cen uuid NOT NULL,
    code text NOT NULL,
    name text NOT NULL,
    address text,
    phone text,
    active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT "PK_locations" PRIMARY KEY (id)
);

CREATE TABLE inventory.movement_types (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    cen uuid NOT NULL,
    code text NOT NULL,
    name text NOT NULL,
    "Description" text,
    movement_direction text NOT NULL,
    active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT "PK_movement_types" PRIMARY KEY (id)
);

CREATE TABLE inventory.movements (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    cen uuid NOT NULL,
    company_id integer NOT NULL,
    company_cen uuid NOT NULL,
    location_id integer NOT NULL,
    location_cen uuid NOT NULL,
    warehouse_id integer NOT NULL,
    warehouse_cen uuid NOT NULL,
    product_id integer NOT NULL,
    product_cen uuid NOT NULL,
    movement_type_id integer NOT NULL,
    movement_type_cen uuid NOT NULL,
    quantity numeric(12,2) NOT NULL,
    balance_before numeric(12,2) NOT NULL,
    balance_after numeric(12,2) NOT NULL,
    reference text,
    notes text,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT "PK_movements" PRIMARY KEY (id)
);

CREATE TABLE inventory.operation_documents (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    cen uuid NOT NULL,
    company_id integer NOT NULL,
    company_cen uuid NOT NULL,
    location_id integer NOT NULL,
    location_cen uuid NOT NULL,
    warehouse_id integer NOT NULL,
    warehouse_cen uuid NOT NULL,
    document_number text NOT NULL,
    operation_type text NOT NULL,
    status text NOT NULL,
    reference text,
    notes text,
    created_at timestamp with time zone NOT NULL,
    confirmed_at timestamp with time zone,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT "PK_operation_documents" PRIMARY KEY (id)
);

CREATE TABLE inventory.products (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    cen uuid NOT NULL,
    company_id integer NOT NULL,
    company_cen uuid NOT NULL,
    code text NOT NULL,
    sku text NOT NULL,
    name text NOT NULL,
    description text,
    category_id integer,
    category_cen uuid,
    unit_measure_id integer,
    unit_measure_cen uuid,
    price numeric(12,2) NOT NULL,
    cost numeric(12,2) NOT NULL,
    track_stock boolean NOT NULL,
    is_out_of_stock boolean NOT NULL,
    active boolean NOT NULL,
    station_code text,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT "PK_products" PRIMARY KEY (id)
);

CREATE TABLE inventory.stock (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    cen uuid NOT NULL,
    company_id integer NOT NULL,
    company_cen uuid NOT NULL,
    location_id integer NOT NULL,
    location_cen uuid NOT NULL,
    warehouse_id integer NOT NULL,
    warehouse_cen uuid NOT NULL,
    product_id integer NOT NULL,
    product_cen uuid NOT NULL,
    quantity numeric(12,2) NOT NULL,
    min_quantity numeric(12,2) NOT NULL,
    max_quantity numeric(12,2),
    last_counted_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT "PK_stock" PRIMARY KEY (id)
);

CREATE TABLE inventory.units_measure (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    cen uuid NOT NULL,
    code text NOT NULL,
    name text NOT NULL,
    abbreviation text,
    active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT "PK_units_measure" PRIMARY KEY (id)
);

CREATE TABLE inventory.warehouses (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    cen uuid NOT NULL,
    company_id integer NOT NULL,
    company_cen uuid NOT NULL,
    location_id integer NOT NULL,
    location_cen uuid NOT NULL,
    code text NOT NULL,
    name text NOT NULL,
    description text,
    active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT "PK_warehouses" PRIMARY KEY (id)
);

CREATE TABLE inventory.operation_document_items (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    cen uuid NOT NULL,
    document_id integer NOT NULL,
    document_cen uuid NOT NULL,
    product_id integer NOT NULL,
    product_cen uuid NOT NULL,
    quantity numeric(12,2) NOT NULL,
    notes text,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT "PK_operation_document_items" PRIMARY KEY (id),
    CONSTRAINT "FK_operation_document_items_operation_documents_document_id" FOREIGN KEY (document_id) REFERENCES inventory.operation_documents (id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX "IX_categories_cen" ON inventory.categories (cen);

CREATE UNIQUE INDEX "IX_categories_company_cen_code" ON inventory.categories (company_cen, code);

CREATE UNIQUE INDEX "IX_companies_cen" ON inventory.companies (cen);

CREATE UNIQUE INDEX "IX_locations_cen" ON inventory.locations (cen);

CREATE UNIQUE INDEX "IX_movement_types_cen" ON inventory.movement_types (cen);

CREATE UNIQUE INDEX "IX_movements_cen" ON inventory.movements (cen);

CREATE UNIQUE INDEX "IX_operation_document_items_cen" ON inventory.operation_document_items (cen);

CREATE INDEX "IX_operation_document_items_document_id" ON inventory.operation_document_items (document_id);

CREATE UNIQUE INDEX "IX_operation_documents_cen" ON inventory.operation_documents (cen);

CREATE UNIQUE INDEX "IX_products_cen" ON inventory.products (cen);

CREATE UNIQUE INDEX "IX_products_company_cen_code" ON inventory.products (company_cen, code);

CREATE UNIQUE INDEX "IX_stock_cen" ON inventory.stock (cen);

CREATE UNIQUE INDEX "IX_units_measure_cen" ON inventory.units_measure (cen);

CREATE UNIQUE INDEX "IX_warehouses_cen" ON inventory.warehouses (cen);

INSERT INTO inventory."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260518023624_InitialCreate', '9.0.4');

COMMIT;

