// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sales.Api.Infrastructure.Persistence;

#nullable disable

namespace Sales.Api.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SalesDbContext))]
    [Migration("20260518023627_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("sales")
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sales.Api.Domain.Entities.Command", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("Cen")
                        .HasColumnType("uuid")
                        .HasColumnName("cen");

                    b.Property<string>("CommandNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("command_number");

                    b.Property<Guid>("CompanyCen")
                        .HasColumnType("uuid")
                        .HasColumnName("company_cen");

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsReorder")
                        .HasColumnType("boolean")
                        .HasColumnName("is_reorder");

                    b.Property<Guid>("LocationCen")
                        .HasColumnType("uuid")
                        .HasColumnName("location_cen");

                    b.Property<int>("LocationId")
                        .HasColumnType("integer")
                        .HasColumnName("location_id");

                    b.Property<DateTime?>("ReadyAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ready_at");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<Guid>("StationCen")
                        .HasColumnType("uuid")
                        .HasColumnName("station_cen");

                    b.Property<int>("StationId")
                        .HasColumnType("integer")
                        .HasColumnName("station_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("TicketCen")
                        .HasColumnType("uuid")
                        .HasColumnName("ticket_cen");

                    b.Property<int>("TicketId")
                        .HasColumnType("integer")
                        .HasColumnName("ticket_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Cen")
                        .IsUnique();

                    b.ToTable("commands", "sales");
                });

            modelBuilder.Entity("Sales.Api.Domain.Entities.CommandItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("Cen")
                        .HasColumnType("uuid")
                        .HasColumnName("cen");

                    b.Property<Guid>("CommandCen")
                        .HasColumnType("uuid")
                        .HasColumnName("command_cen");

                    b.Property<int>("CommandId")
                        .HasColumnType("integer")
                        .HasColumnName("command_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<Guid>("ProductCen")
                        .HasColumnType("uuid")
                        .HasColumnName("product_cen");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("quantity");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("TicketItemCen")
                        .HasColumnType("uuid")
                        .HasColumnName("ticket_item_cen");

                    b.Property<int>("TicketItemId")
                        .HasColumnType("integer")
                        .HasColumnName("ticket_item_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Cen")
                        .IsUnique();

                    b.HasIndex("CommandId");

                    b.ToTable("command_items", "sales");
                });

            modelBuilder.Entity("Sales.Api.Domain.Entities.CommandStation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<Guid>("Cen")
                        .HasColumnType("uuid")
                        .HasColumnName("cen");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<Guid>("CompanyCen")
                        .HasColumnType("uuid")
                        .HasColumnName("company_cen");

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("StationType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("station_type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Cen")
                        .IsUnique();

                    b.ToTable("command_stations", "sales");
                });

            modelBuilder.Entity("Sales.Api.Domain.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("Amount");

                    b.Property<Guid>("Cen")
                        .HasColumnType("uuid")
                        .HasColumnName("Cen");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("PaidBy")
                        .HasColumnType("text")
                        .HasColumnName("PaidBy");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("PaymentMethod");

                    b.Property<string>("Reference")
                        .HasColumnType("text")
                        .HasColumnName("Reference");

                    b.Property<Guid>("TicketCen")
                        .HasColumnType("uuid")
                        .HasColumnName("TicketCen");

                    b.Property<int>("TicketId")
                        .HasColumnType("integer")
                        .HasColumnName("TicketId");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("Cen")
                        .IsUnique();

                    b.ToTable("Payment", "sales");
                });

            modelBuilder.Entity("Sales.Api.Domain.Entities.SalesCompany", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("Cen")
                        .HasColumnType("uuid")
                        .HasColumnName("Cen");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.HasIndex("Cen")
                        .IsUnique();

                    b.ToTable("Company", "sales");
                });

            modelBuilder.Entity("Sales.Api.Domain.Entities.SalesLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("Cen")
                        .HasColumnType("uuid")
                        .HasColumnName("Cen");

                    b.Property<Guid>("CompanyCen")
                        .HasColumnType("uuid")
                        .HasColumnName("CompanyCen");

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer")
                        .HasColumnName("CompanyId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.HasIndex("Cen")
                        .IsUnique();

                    b.ToTable("Location", "sales");
                });

            modelBuilder.Entity("Sales.Api.Domain.Entities.TaxConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("Cen")
                        .HasColumnType("uuid")
                        .HasColumnName("cen");

                    b.Property<Guid>("CompanyCen")
                        .HasColumnType("uuid")
                        .HasColumnName("company_cen");

                    b.Property<decimal>("TaxRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("tax_rate");

                    b.HasKey("Id");

                    b.HasIndex("CompanyCen")
                        .IsUnique();

                    b.ToTable("tax_configuration", "sales");
                });

            modelBuilder.Entity("Sales.Api.Domain.Entities.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("Cen")
                        .HasColumnType("uuid")
                        .HasColumnName("Cen");

                    b.Property<Guid>("CompanyCen")
                        .HasColumnType("uuid")
                        .HasColumnName("CompanyCen");

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer")
                        .HasColumnName("CompanyId");

                    b.Property<Guid>("LocationCen")
                        .HasColumnType("uuid")
                        .HasColumnName("LocationCen");

                    b.Property<int>("LocationId")
                        .HasColumnType("integer")
                        .HasColumnName("LocationId");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Status");

                    b.Property<string>("TableCode")
                        .HasColumnType("text")
                        .HasColumnName("TableCode");

                    b.Property<string>("TicketNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("TicketNumber");

                    b.Property<Guid?>("VendorCen")
                        .HasColumnType("uuid")
                        .HasColumnName("VendorCen");

                    b.Property<int?>("VendorId")
                        .HasColumnType("integer")
                        .HasColumnName("VendorId");

                    b.HasKey("Id");

                    b.HasIndex("Cen")
                        .IsUnique();

                    b.ToTable("Ticket", "sales");
                });

            modelBuilder.Entity("Sales.Api.Domain.Entities.TicketItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("Cen")
                        .HasColumnType("uuid")
                        .HasColumnName("Cen");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("Notes");

                    b.Property<Guid>("ProductCen")
                        .HasColumnType("uuid")
                        .HasColumnName("ProductCen");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("ProductId");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("Quantity");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Status");

                    b.Property<Guid>("TicketCen")
                        .HasColumnType("uuid")
                        .HasColumnName("TicketCen");

                    b.Property<int>("TicketId")
                        .HasColumnType("integer")
                        .HasColumnName("TicketId");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("UnitPrice");

                    b.HasKey("Id");

                    b.HasIndex("Cen")
                        .IsUnique();

                    b.HasIndex("TicketId");

                    b.ToTable("TicketItem", "sales");
                });

            modelBuilder.Entity("Sales.Api.Domain.Entities.Vendor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("Active");

                    b.Property<Guid>("Cen")
                        .HasColumnType("uuid")
                        .HasColumnName("Cen");

                    b.Property<Guid>("CompanyCen")
                        .HasColumnType("uuid")
                        .HasColumnName("CompanyCen");

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer")
                        .HasColumnName("CompanyId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("Email");

                    b.Property<bool>("IsWaiter")
                        .HasColumnType("boolean")
                        .HasColumnName("IsWaiter");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Name");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("Phone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("Cen")
                        .IsUnique();

                    b.ToTable("Vendor", "sales");
                });

            modelBuilder.Entity("Sales.Api.Domain.Entities.CommandItem", b =>
                {
                    b.HasOne("Sales.Api.Domain.Entities.Command", null)
                        .WithMany("Items")
                        .HasForeignKey("CommandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sales.Api.Domain.Entities.TicketItem", b =>
                {
                    b.HasOne("Sales.Api.Domain.Entities.Ticket", null)
                        .WithMany("Items")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sales.Api.Domain.Entities.Command", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Sales.Api.Domain.Entities.Ticket", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
