DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'purchases') THEN
        CREATE SCHEMA purchases;
    END IF;
END $EF$;
CREATE TABLE IF NOT EXISTS purchases."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'purchases') THEN
        CREATE SCHEMA purchases;
    END IF;
END $EF$;

CREATE TABLE purchases.orders (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    cen uuid NOT NULL,
    company_id integer NOT NULL,
    company_cen uuid NOT NULL,
    supplier text NOT NULL,
    supplier_cen uuid,
    date timestamp with time zone NOT NULL,
    status text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT "PK_orders" PRIMARY KEY ("Id")
);

CREATE TABLE purchases.order_items (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    cen uuid NOT NULL,
    order_id integer NOT NULL,
    order_cen uuid NOT NULL,
    product_id integer NOT NULL,
    product_cen uuid NOT NULL,
    quantity numeric(12,2) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT "PK_order_items" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_order_items_orders_order_id" FOREIGN KEY (order_id) REFERENCES purchases.orders ("Id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX "IX_order_items_cen" ON purchases.order_items (cen);

CREATE INDEX "IX_order_items_order_id" ON purchases.order_items (order_id);

CREATE UNIQUE INDEX "IX_orders_cen" ON purchases.orders (cen);

INSERT INTO purchases."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260518023623_InitialCreate', '9.0.4');

INSERT INTO purchases."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260522233555_CreateSuppliersTable', '9.0.4');

COMMIT;

