DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'sales') THEN
        CREATE SCHEMA sales;
    END IF;
END $EF$;
CREATE TABLE IF NOT EXISTS sales."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'sales') THEN
        CREATE SCHEMA sales;
    END IF;
END $EF$;

CREATE TABLE sales.command_stations (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    cen uuid NOT NULL,
    company_id integer NOT NULL,
    company_cen uuid NOT NULL,
    code text NOT NULL,
    name text NOT NULL,
    station_type text NOT NULL,
    description text,
    active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT "PK_command_stations" PRIMARY KEY ("Id")
);

CREATE TABLE sales.commands (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    cen uuid NOT NULL,
    company_id integer NOT NULL,
    company_cen uuid NOT NULL,
    location_id integer NOT NULL,
    location_cen uuid NOT NULL,
    ticket_id integer NOT NULL,
    ticket_cen uuid NOT NULL,
    station_id integer NOT NULL,
    station_cen uuid NOT NULL,
    command_number text NOT NULL,
    status text NOT NULL,
    is_reorder boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    sent_at timestamp with time zone,
    ready_at timestamp with time zone,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT "PK_commands" PRIMARY KEY ("Id")
);

CREATE TABLE sales."Company" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Cen" uuid NOT NULL,
    "Name" text NOT NULL,
    CONSTRAINT "PK_Company" PRIMARY KEY ("Id")
);

CREATE TABLE sales."Location" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Cen" uuid NOT NULL,
    "CompanyId" integer NOT NULL,
    "CompanyCen" uuid NOT NULL,
    "Name" text NOT NULL,
    CONSTRAINT "PK_Location" PRIMARY KEY ("Id")
);

CREATE TABLE sales."Payment" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Cen" uuid NOT NULL,
    "TicketId" integer NOT NULL,
    "TicketCen" uuid NOT NULL,
    "PaymentMethod" text NOT NULL,
    "Amount" numeric(12,2) NOT NULL,
    "Reference" text,
    "PaidBy" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Payment" PRIMARY KEY ("Id")
);

CREATE TABLE sales.tax_configuration (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    cen uuid NOT NULL,
    company_cen uuid NOT NULL,
    tax_rate numeric(5,2) NOT NULL,
    CONSTRAINT "PK_tax_configuration" PRIMARY KEY ("Id")
);

CREATE TABLE sales."Ticket" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Cen" uuid NOT NULL,
    "CompanyId" integer NOT NULL,
    "CompanyCen" uuid NOT NULL,
    "LocationId" integer NOT NULL,
    "LocationCen" uuid NOT NULL,
    "TicketNumber" text NOT NULL,
    "VendorId" integer,
    "VendorCen" uuid,
    "TableCode" text,
    "Status" text NOT NULL,
    CONSTRAINT "PK_Ticket" PRIMARY KEY ("Id")
);

CREATE TABLE sales."Vendor" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Cen" uuid NOT NULL,
    "CompanyId" integer NOT NULL,
    "CompanyCen" uuid NOT NULL,
    "Name" text NOT NULL,
    "Email" text,
    "Phone" text,
    "IsWaiter" boolean NOT NULL,
    "Active" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Vendor" PRIMARY KEY ("Id")
);

CREATE TABLE sales.command_items (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    cen uuid NOT NULL,
    command_id integer NOT NULL,
    command_cen uuid NOT NULL,
    ticket_item_id integer NOT NULL,
    ticket_item_cen uuid NOT NULL,
    product_id integer NOT NULL,
    product_cen uuid NOT NULL,
    quantity numeric(12,2) NOT NULL,
    status text NOT NULL,
    notes text,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT "PK_command_items" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_command_items_commands_command_id" FOREIGN KEY (command_id) REFERENCES sales.commands ("Id") ON DELETE CASCADE
);

CREATE TABLE sales."TicketItem" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Cen" uuid NOT NULL,
    "TicketId" integer NOT NULL,
    "TicketCen" uuid NOT NULL,
    "ProductId" integer NOT NULL,
    "ProductCen" uuid NOT NULL,
    "Quantity" numeric(12,2) NOT NULL,
    "UnitPrice" numeric(12,2) NOT NULL,
    "Status" text NOT NULL,
    "Notes" text,
    CONSTRAINT "PK_TicketItem" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_TicketItem_Ticket_TicketId" FOREIGN KEY ("TicketId") REFERENCES sales."Ticket" ("Id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX "IX_command_items_cen" ON sales.command_items (cen);

CREATE INDEX "IX_command_items_command_id" ON sales.command_items (command_id);

CREATE UNIQUE INDEX "IX_command_stations_cen" ON sales.command_stations (cen);

CREATE UNIQUE INDEX "IX_commands_cen" ON sales.commands (cen);

CREATE UNIQUE INDEX "IX_Company_Cen" ON sales."Company" ("Cen");

CREATE UNIQUE INDEX "IX_Location_Cen" ON sales."Location" ("Cen");

CREATE UNIQUE INDEX "IX_Payment_Cen" ON sales."Payment" ("Cen");

CREATE UNIQUE INDEX "IX_tax_configuration_company_cen" ON sales.tax_configuration (company_cen);

CREATE UNIQUE INDEX "IX_Ticket_Cen" ON sales."Ticket" ("Cen");

CREATE UNIQUE INDEX "IX_TicketItem_Cen" ON sales."TicketItem" ("Cen");

CREATE INDEX "IX_TicketItem_TicketId" ON sales."TicketItem" ("TicketId");

CREATE UNIQUE INDEX "IX_Vendor_Cen" ON sales."Vendor" ("Cen");

INSERT INTO sales."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260518023627_InitialCreate', '9.0.4');

COMMIT;

